### ISSUE TITLE
ReferenceError: requestedHyena is not defined

### ISSUE THREAD

**Issue by Langer004** [PatrickAlphaC/html-js-ethers-connect#1]
Trying to create buttons to work with the Advanced Collectible NFT I made using your videos, (instead of dog i am using Hyenas) i run into this error in the Console when I go to execute the contract. 

ReferenceError: requestedHyena is not defined
    at Object.execute (bundle.js:908:32)
    at HTMLButtonElement.onclick (index.html:9:66)

I am also trying to use this on Rinkeby as I couldn't get ganache ganache figured out. 😅

repo here: **https://github.com/Langer004/HHDHelp**

**Comment by PatrickAlphaC** [comment]
Hi Langer! I won't be able to debug you're specific repo, and right now I don't have enough information to help with this specific issue.

I have no idea what `requestedHyena` is. 

I'm closing this issue for now, but if you clarify what you're running into, I or someone else may be able to help!

Following along with this video will give you a process to debug as well. Thanks!

https://www.youtube.com/watch?v=XT8STflvwNo
